using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CA.Portal.Tests
{
    [TestClass]
    public class BusinessLogic_CA
    {
        [TestMethod]
        public void Test_Request()
        {
//            var c = new CA.Portal.BusinessLogic.CA();

//            string req = @"-----BEGIN NEW CERTIFICATE REQUEST-----
//MIIEUDCCAzgCAQAwZzELMAkGA1UEBhMCR0IxEDAOBgNVBAgMB1Rlc3RpbmcxEDAO
//BgNVBAcMB1Rlc3RpbmcxEDAOBgNVBAoMB1Rlc3RpbmcxEDAOBgNVBAsMB1Rlc3Rp
//bmcxEDAOBgNVBAMMB1Rlc3RpbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
//AoIBAQCwjW01kdeQ5QvBLsr4LHdAxjIOYyEsvMgb1Za/dyLACAhlpp+fkVIlMsPo
//NAIxLSf7yLmHG2rbNGGvQPfUIOvdLi9GM+8o5E6OL/Q/TKkCHPG+/RfsijpiR3bi
//x6t8ESHvv6ozcdakLVJzyvCymReA5Th7H+gaYNEZ6TbEvhZbiSAmx8W7oF1TQT5b
//o2jPPUJBdcFGgNGkOtiv0cq6DPWh50hJ70fSmg4CBoWqThcYV4B08jUnW2/8xEIH
//xc1XiBySl1RTQ8yc/zHRwD6Hb5cmY1YNsDma3tJA3xnaOUAynWCGuA093vjOL2qp
//hztm+9NhTBEK7F7AmGRL81kjlDfhAgMBAAGgggGiMBwGCisGAQQBgjcNAgMxDhYM
//MTAuMC4xMDI0MC4yMDwGCSsGAQQBgjcVFDEvMC0CAQUMCldJTjEwLWlNQUMMD1dJ
//TjEwLUlNQUNcQW5keQwLSW5ldE1nci5leGUwcgYKKwYBBAGCNw0CAjFkMGICAQEe
//WgBNAGkAYwByAG8AcwBvAGYAdAAgAFIAUwBBACAAUwBDAGgAYQBuAG4AZQBsACAA
//QwByAHkAcAB0AG8AZwByAGEAcABoAGkAYwAgAFAAcgBvAHYAaQBkAGUAcgMBADCB
//zwYJKoZIhvcNAQkOMYHBMIG+MA4GA1UdDwEB/wQEAwIE8DATBgNVHSUEDDAKBggr
//BgEFBQcDATB4BgkqhkiG9w0BCQ8EazBpMA4GCCqGSIb3DQMCAgIAgDAOBggqhkiG
//9w0DBAICAIAwCwYJYIZIAWUDBAEqMAsGCWCGSAFlAwQBLTALBglghkgBZQMEAQIw
//CwYJYIZIAWUDBAEFMAcGBSsOAwIHMAoGCCqGSIb3DQMHMB0GA1UdDgQWBBShbEnI
//nEu5k2P/7uekzN3pB42x6DANBgkqhkiG9w0BAQUFAAOCAQEApMSukY+wniku9fWa
//unFgufwg+s5o6sl/Sh5joXaM4Lyk75xJfBaMWnV775n+TaFyawUMW97oWCedFe5J
//GOzgw54eOwloqNw5AK42JJYmygQefc0jGqsidLa4y4Zc6H8VCNRspaQAlxB153rj
//io2eLlknGZ/UI0hr6UFGLzn7sDxY0yVc9e70lCv0xsr/OuHYOfoFFHnJj8GSe0mJ
//eFyg2ZUxTgB0aVG2N9xWTmrUsbh52ZpP5tatWRNt1ldJ3jmfnoMBCB75g17Wo7/3
//DPf28SkzRb8ZOWD3em6Zg5/BnYyxsYxrFaowF5SH4xJ7/f0iqGhF7Q6oT3/o4iYZ
//eIUzTQ==
//-----END NEW CERTIFICATE REQUEST-----
//";

//            c.Request(req);
        }
    }
}
